plugins {
    id 'com.android.application'
}
android {
    namespace 'id.my.hiemz.wms'
    compileSdk 34
    defaultConfig {
        applicationId "id.my.hiemz.wms"
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName "1.3-wh-rpa"
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
